### PR TITLE
[minor] MDL-35628: Remove dirname() where possible.

### PR DESCRIPTION
**Pull request by sk-unikent**
I know this is tiny... but it keeps flagging up on my code checker ;)

### CODE REVIEW

**Comment by gjb2048** [comment]
Hi Skyler,

Ok, thanks :) - so I can understand things, what is the code checker error please?

G

**Comment by sk-unikent** [comment]
Hey,

It is just "dirname(__FILE__) should be replaced with __DIR__.".
I added it to our checks after MDL-35628 was merged, it's a minor performance thing.

-Sky

**Comment by gjb2048** [comment]
Hi Sky,

Thank you :) - makes sense.

G

**Comment by gjb2048** [comment]
Umm, Sky, do you need this backported to M3.2- versions?

**Comment by sk-unikent** [comment]
I don't, it's a very minor change.. thanks!

**Pull request merged**
