### PR TITLE
ADD composer.json

### PR DESCRIPTION
**Pull request by michaelmeneses**

### CODE REVIEW

**Comment by michaelmeneses** [comment]
Hi @gjb2048. You can resolve this PR?

**Comment by michaelmeneses** [comment]
Hi,

Add composer.json will allow use PHP Composer to manage dependencies in Moodle.

This only will possible with composer.json.

See topic must recent: https://moodle.org/mod/forum/discuss.php?d=361703

**Comment by gjb2048** [comment]
Dear @michaelmeneses,

That's an argument, not a set of answers.  You _have_ to convince me to spend my time dealing with and maintaining this.

Gareth

**Comment by michaelmeneses** [comment]
Fork solves for me: https://satis.middag.com.br/#moodle-format_topcoll

**Pull request closed without merging**
