### PR TITLE
format_topcoll: Treat themes using Boost as a parent the same as Boost

### PR DESCRIPTION
**Pull request by tonyjbutler**
Currently the layout is broken if using a custom theme based on Boost (and using it as a parent).

### CODE REVIEW

**Comment by gjb2048** [comment]
Interesting for contributed themes.  But.... might be an issue of functional conflict if the child theme overrides the get_row_class and get_column_class as intended and find they don't work.  The actual solution looks as if it could be more efficient.

**Comment by gjb2048** [comment]
Ok, $THEME->parents in a theme config.php file is an array, e.g.

`$THEME->parents = array('bootstrapbase');`

so why are you not using the PHP 'in_array' function if '$page->theme->parents' is not empty?  Then use the '===' comparitor.  Ok, I need to change things too.

**Comment by tonyjbutler** [comment]
OK, I've improved the efficiency as per your suggestion.

**Comment by gjb2048** [comment]
Thanks Tony.

**Pull request merged**
