### PR TITLE
Fix for php unit test failure

### PR DESCRIPTION
**Pull request by Anupamatd**
Hi Gareth,

Please review this.

Thanks,
Anupama

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks Anupama,

Clearly there is a coding standard issue https://travis-ci.org/gjb2048/moodle-format_topcoll/jobs/506136216#L754-L755.  Please fix and resubmit as a single commit.

Gareth

**Comment by Anupamatd** [comment]
Hi Gareth,

Fixed coding issue.

Thanks,
Anupama

**Comment by gjb2048** [comment]
Thanks Anu.

**Comment by gjb2048** [comment]
Note, MDL that caused this is MDL-62680 so that can work out the respective M3.5 and 3.4 versions to adjust the patch against!

**Comment by gjb2048** [comment]
Right.

Anu, sorry, but really, really NOT happy.  The version you put into the patch is a M3.5 version number and in fact not a M3.6 number and it is the actual release date of M3.5 and not the actual number when MDL-62680 was merged into Moodle core.

If people make mistakes then fair enough.  So, what happened please?  How did you come up with the number '2018051700' in the patch?

Now this means I have to do hard work of sorting out the mess.  So the tests need to be accurate and operate before and after the 'exact' version that MDL-62680 was integrated into.

Please, kindly explain.

**Pull request merged**
